
LooseWorkout_plan = {
                50 : {"Weekly structure":["4 Strength Days", "2 Cardio Days", "1 Active Recovery Day"],"Cardio Type":["Brisk walking", "jogging", "cycling", "elliptical", "HIIT(Jump squats, mountain climbers, burpees)"],"Key Exercises":["Squats","Push-ups","Dumbbell Rows","Lunges","Bench Press","Romanian Deadlifts"],"Duration":"45–60 minutes","Calorie Deficit Recommendation":"300–500 calories below maintenance","Protein Guidelines":"0.7–1g per lb bodyweight","Expected Weekly Weight Loss":"0.5–1 lbs"}, 
                70  : {"Weekly structure":["3 Strength Days", "2 Cardio Days", "1 Active Recovery Day","1 Full Rest Day"],"Cardio Type":["Brisk walking", "cycling", "elliptical", "swimming"],"Key Exercises":["Goblet Squats","Dumbbell Chest Press","Seated Rows","Leg Press","Bench Press","Romanian Deadlift"],"Duration":"40–60 minutes","Calorie Deficit Recommendation":"300–400 calories below maintenance","Protein Guidelines":"Protein at every meal","Expected Weekly Weight Loss":"0.5–1 lbs"}, 
                100 : {"Weekly structure":["3 Strength/Resistance Days", "2 Cardio Days (low impact)", "1  Mobility / Balance Day","1 Full Rest Day"],"Cardio Type":["Walking (flat terrain)", "stationary bike", "elliptical", "swimming"],"Key Exercises":["Chair Squats","Wall Push-ups","Resistance Band Rows","Step-ups","Bird Dog"],"Duration":"30–50 minutes","Calorie Deficit Recommendation":"250–300 calories below maintenance","Protein Guidelines":"25–30g per meal","Expected Weekly Weight Loss":"0.25–0.5 lbs"}} 
#print(LooseWorkout_plan[50])
tempag =50
print(LooseWorkout_plan[tempag]["Weekly structure"],"\n\n","Cardio Type",LooseWorkout_plan[50]["Cardio Type"])


GainWorkout_plan = {
                50 : {"Weekly structure":["5 Training Days", "2 Recovery Days"],"Cardio Type":["Light walking"],"Key Exercises":["Bench Press","Squats","Deadlifts","Pull-ups","Barbell Curls"],"Duration":"45–70 minutes","Calorie Recommendation":"300–400 calories above maintenance","Protein Guidelines":"0.7–1g per lb bodyweight","Expected Weekly Weight Gain":"0.25–0.375 lbs"}, 
                70  : {"Weekly structure":["4 Strength Days", "2 Light Activity Days", "1 Full Rest Day"],"Cardio Type":["30 min Brisk walking", "light cardio 15 -20 mins"],"Key Exercises":["Dumbbell Chest Press","Goblet Squats","Lat Pulldown","Romanian Deadlifts","Plank"],"Duration":"45–60 minutes","Calorie Recommendation":"250–350 calories above maintenance","Protein Guidelines":"0.8–1g per lb bodyweight","Expected Weekly Weight Loss":"0.125–0.25 lbs"}, 
                100 : {"Weekly structure":["3 Strength Days", "2 Light Movement Days", "2 Full Rest Days"],"Cardio Type":["20–30 minute brisk walk or cycling"],"Key Exercises":["Chair Squats","Wall Push-ups","Seated Dumbbell Shoulder Press","Resistance Band Rows"],"Duration":"30–45 minutes","Calorie Recommendation":"Small surplus (Eat slightly more than usual)","Protein Guidelines":"Protein at every meal (eggs, fish, chicken, lentils, Greek yogurt)","Expected Weekly Weight Loss":"Less than 0.125 lbs "}} 
